//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.loginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="loginServiceReference.LoginWebServiceSoap")]
    public interface LoginWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoPharmacyIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyID", ReplyAction="*")]
        Client.loginServiceReference.AutoPharmacyIDResponse AutoPharmacyID(Client.loginServiceReference.AutoPharmacyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyID", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.loginServiceReference.AutoPharmacyIDResponse> AutoPharmacyIDAsync(Client.loginServiceReference.AutoPharmacyIDRequest request);
        
        // CODEGEN: Generating message contract since element name PharmacyID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPharmacy", ReplyAction="*")]
        Client.loginServiceReference.insertPharmacyResponse insertPharmacy(Client.loginServiceReference.insertPharmacyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPharmacy", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.loginServiceReference.insertPharmacyResponse> insertPharmacyAsync(Client.loginServiceReference.insertPharmacyRequest request);
        
        // CODEGEN: Generating message contract since element name AutoUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUserId", ReplyAction="*")]
        Client.loginServiceReference.AutoUserIdResponse AutoUserId(Client.loginServiceReference.AutoUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.loginServiceReference.AutoUserIdResponse> AutoUserIdAsync(Client.loginServiceReference.AutoUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        Client.loginServiceReference.loginResponse login(Client.loginServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.loginServiceReference.loginResponse> loginAsync(Client.loginServiceReference.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyID", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.AutoPharmacyIDRequestBody Body;
        
        public AutoPharmacyIDRequest() {
        }
        
        public AutoPharmacyIDRequest(Client.loginServiceReference.AutoPharmacyIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoPharmacyIDRequestBody {
        
        public AutoPharmacyIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.AutoPharmacyIDResponseBody Body;
        
        public AutoPharmacyIDResponse() {
        }
        
        public AutoPharmacyIDResponse(Client.loginServiceReference.AutoPharmacyIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoPharmacyIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoPharmacyIDResult;
        
        public AutoPharmacyIDResponseBody() {
        }
        
        public AutoPharmacyIDResponseBody(string AutoPharmacyIDResult) {
            this.AutoPharmacyIDResult = AutoPharmacyIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPharmacyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPharmacy", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.insertPharmacyRequestBody Body;
        
        public insertPharmacyRequest() {
        }
        
        public insertPharmacyRequest(Client.loginServiceReference.insertPharmacyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPharmacyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PharmacyID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public insertPharmacyRequestBody() {
        }
        
        public insertPharmacyRequestBody(string PharmacyID, string Name, string Location, string ContactNumber, string Username, string Password) {
            this.PharmacyID = PharmacyID;
            this.Name = Name;
            this.Location = Location;
            this.ContactNumber = ContactNumber;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPharmacyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPharmacyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.insertPharmacyResponseBody Body;
        
        public insertPharmacyResponse() {
        }
        
        public insertPharmacyResponse(Client.loginServiceReference.insertPharmacyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPharmacyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertPharmacyResult;
        
        public insertPharmacyResponseBody() {
        }
        
        public insertPharmacyResponseBody(string insertPharmacyResult) {
            this.insertPharmacyResult = insertPharmacyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoUserId", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.AutoUserIdRequestBody Body;
        
        public AutoUserIdRequest() {
        }
        
        public AutoUserIdRequest(Client.loginServiceReference.AutoUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoUserIdRequestBody {
        
        public AutoUserIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.AutoUserIdResponseBody Body;
        
        public AutoUserIdResponse() {
        }
        
        public AutoUserIdResponse(Client.loginServiceReference.AutoUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoUserIdResult;
        
        public AutoUserIdResponseBody() {
        }
        
        public AutoUserIdResponseBody(string AutoUserIdResult) {
            this.AutoUserIdResult = AutoUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Client.loginServiceReference.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.loginServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Client.loginServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginWebServiceSoapChannel : Client.loginServiceReference.LoginWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWebServiceSoapClient : System.ServiceModel.ClientBase<Client.loginServiceReference.LoginWebServiceSoap>, Client.loginServiceReference.LoginWebServiceSoap {
        
        public LoginWebServiceSoapClient() {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.loginServiceReference.AutoPharmacyIDResponse Client.loginServiceReference.LoginWebServiceSoap.AutoPharmacyID(Client.loginServiceReference.AutoPharmacyIDRequest request) {
            return base.Channel.AutoPharmacyID(request);
        }
        
        public string AutoPharmacyID() {
            Client.loginServiceReference.AutoPharmacyIDRequest inValue = new Client.loginServiceReference.AutoPharmacyIDRequest();
            inValue.Body = new Client.loginServiceReference.AutoPharmacyIDRequestBody();
            Client.loginServiceReference.AutoPharmacyIDResponse retVal = ((Client.loginServiceReference.LoginWebServiceSoap)(this)).AutoPharmacyID(inValue);
            return retVal.Body.AutoPharmacyIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.loginServiceReference.AutoPharmacyIDResponse> Client.loginServiceReference.LoginWebServiceSoap.AutoPharmacyIDAsync(Client.loginServiceReference.AutoPharmacyIDRequest request) {
            return base.Channel.AutoPharmacyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.loginServiceReference.AutoPharmacyIDResponse> AutoPharmacyIDAsync() {
            Client.loginServiceReference.AutoPharmacyIDRequest inValue = new Client.loginServiceReference.AutoPharmacyIDRequest();
            inValue.Body = new Client.loginServiceReference.AutoPharmacyIDRequestBody();
            return ((Client.loginServiceReference.LoginWebServiceSoap)(this)).AutoPharmacyIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.loginServiceReference.insertPharmacyResponse Client.loginServiceReference.LoginWebServiceSoap.insertPharmacy(Client.loginServiceReference.insertPharmacyRequest request) {
            return base.Channel.insertPharmacy(request);
        }
        
        public string insertPharmacy(string PharmacyID, string Name, string Location, string ContactNumber, string Username, string Password) {
            Client.loginServiceReference.insertPharmacyRequest inValue = new Client.loginServiceReference.insertPharmacyRequest();
            inValue.Body = new Client.loginServiceReference.insertPharmacyRequestBody();
            inValue.Body.PharmacyID = PharmacyID;
            inValue.Body.Name = Name;
            inValue.Body.Location = Location;
            inValue.Body.ContactNumber = ContactNumber;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            Client.loginServiceReference.insertPharmacyResponse retVal = ((Client.loginServiceReference.LoginWebServiceSoap)(this)).insertPharmacy(inValue);
            return retVal.Body.insertPharmacyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.loginServiceReference.insertPharmacyResponse> Client.loginServiceReference.LoginWebServiceSoap.insertPharmacyAsync(Client.loginServiceReference.insertPharmacyRequest request) {
            return base.Channel.insertPharmacyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.loginServiceReference.insertPharmacyResponse> insertPharmacyAsync(string PharmacyID, string Name, string Location, string ContactNumber, string Username, string Password) {
            Client.loginServiceReference.insertPharmacyRequest inValue = new Client.loginServiceReference.insertPharmacyRequest();
            inValue.Body = new Client.loginServiceReference.insertPharmacyRequestBody();
            inValue.Body.PharmacyID = PharmacyID;
            inValue.Body.Name = Name;
            inValue.Body.Location = Location;
            inValue.Body.ContactNumber = ContactNumber;
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((Client.loginServiceReference.LoginWebServiceSoap)(this)).insertPharmacyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.loginServiceReference.AutoUserIdResponse Client.loginServiceReference.LoginWebServiceSoap.AutoUserId(Client.loginServiceReference.AutoUserIdRequest request) {
            return base.Channel.AutoUserId(request);
        }
        
        public string AutoUserId() {
            Client.loginServiceReference.AutoUserIdRequest inValue = new Client.loginServiceReference.AutoUserIdRequest();
            inValue.Body = new Client.loginServiceReference.AutoUserIdRequestBody();
            Client.loginServiceReference.AutoUserIdResponse retVal = ((Client.loginServiceReference.LoginWebServiceSoap)(this)).AutoUserId(inValue);
            return retVal.Body.AutoUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.loginServiceReference.AutoUserIdResponse> Client.loginServiceReference.LoginWebServiceSoap.AutoUserIdAsync(Client.loginServiceReference.AutoUserIdRequest request) {
            return base.Channel.AutoUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.loginServiceReference.AutoUserIdResponse> AutoUserIdAsync() {
            Client.loginServiceReference.AutoUserIdRequest inValue = new Client.loginServiceReference.AutoUserIdRequest();
            inValue.Body = new Client.loginServiceReference.AutoUserIdRequestBody();
            return ((Client.loginServiceReference.LoginWebServiceSoap)(this)).AutoUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.loginServiceReference.loginResponse Client.loginServiceReference.LoginWebServiceSoap.login(Client.loginServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string Username, string Password) {
            Client.loginServiceReference.loginRequest inValue = new Client.loginServiceReference.loginRequest();
            inValue.Body = new Client.loginServiceReference.loginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            Client.loginServiceReference.loginResponse retVal = ((Client.loginServiceReference.LoginWebServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.loginServiceReference.loginResponse> Client.loginServiceReference.LoginWebServiceSoap.loginAsync(Client.loginServiceReference.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.loginServiceReference.loginResponse> loginAsync(string Username, string Password) {
            Client.loginServiceReference.loginRequest inValue = new Client.loginServiceReference.loginRequest();
            inValue.Body = new Client.loginServiceReference.loginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((Client.loginServiceReference.LoginWebServiceSoap)(this)).loginAsync(inValue);
        }
    }
}
